# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW92SZwFOdY8z8pgeRnW5hLQ6B-wZdqt
"""

# main.py

from fastapi import FastAPI, UploadFile, File
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

from fastapi.middleware.cors import CORSMiddleware
import tensorflow as tf
import numpy as np
from PIL import Image
import io
import gdown

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Load model
MODEL_PATH = "best_mobilenet_cifar10.h5"
GDRIVE_ID = "1aH_d0HNxSEwDdOWVoGzZEe-Pz2c0G3Bi"
if not os.path.exists(MODEL_PATH):
    print("Downloading model from Google Drive...")
    gdown.download(
        f"https://drive.google.com/uc?id={GDRIVE_ID}",
        MODEL_PATH,
        quiet=False
    )
model = tf.keras.models.load_model(
    MODEL_PATH,
    compile=False,
    safe_mode=False
)


# CIFAR-10 class labels
CLASS_NAMES = [
    "airplane", "automobile", "bird", "cat", "deer",
    "dog", "frog", "horse", "ship", "truck"
]

app = FastAPI(title="CIFAR-10 MobileNetV2 API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

def preprocess_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    image = image.resize((96, 96))

    image = np.array(image, dtype=np.float32)
    image = preprocess_input(image)   # 🔴 CRITICAL
    image = np.expand_dims(image, axis=0)

    return image

@app.get("/")
def root():
    return {"status": "API running (MobileNetV2, 96x96)"}

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    image_bytes = await file.read()
    image = preprocess_image(image_bytes)

    preds = model.predict(image)
    class_id = int(np.argmax(preds))
    confidence = float(np.max(preds))

    return {
        "predicted_class": CLASS_NAMES[class_id],
        "confidence": confidence
    }

